#!/usr/bin/env python3
"""Generate the terrain and rock meshes for the Moon Yard worlds.

Uses the standard library only. The output is deterministic: running the
script twice writes byte-identical files.

Usage: generate_assets.py --output-dir DIR
The meshes are written to DIR/<model name>/meshes/.
"""

import argparse
import math
import random
from pathlib import Path
from typing import NamedTuple

ARENA_LENGTH = 7.9
ARENA_WIDTH = 4.4
GRID_STEP = 0.05


class Crater(NamedTuple):
    x: float
    y: float
    diameter: float
    depth: float


class Rock(NamedTuple):
    seed: int
    length: float
    width: float
    height: float


CRATERS = (
    Crater(3.64, 4.00, 0.50, 0.12),
    Crater(3.57, 1.90, 0.45, 0.15),
    Crater(7.44, 2.00, 0.50, 0.18),
)

ROCKS = {
    'rock_a': Rock(11, 0.38, 0.32, 0.22),
    'rock_b': Rock(22, 0.34, 0.30, 0.18),
    'rock_c': Rock(33, 0.40, 0.36, 0.25),
    'rock_d': Rock(44, 0.31, 0.30, 0.16),
}

ROCK_NOISE = 0.15
ROCK_BURY = 0.25
ICOSPHERE_SUBDIVISIONS = 2


def format_float(value):
    text = f'{value:.6f}'
    return '0.000000' if text == '-0.000000' else text


def normalise(v):
    length = math.sqrt(sum(c * c for c in v)) or 1.0
    return tuple(c / length for c in v)


def cross(u, v):
    return (u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0])


def vertex_normals(vertices, faces):
    sums = [[0.0, 0.0, 0.0] for _ in vertices]
    for a, b, c in faces:
        pa, pb, pc = vertices[a], vertices[b], vertices[c]
        u = [pb[k] - pa[k] for k in range(3)]
        v = [pc[k] - pa[k] for k in range(3)]
        n = cross(u, v)
        for i in (a, b, c):
            for k in range(3):
                sums[i][k] += n[k]
    return [normalise(n) for n in sums]


def write_obj(path, name, vertices, faces):
    # gz-physics (DART) crashes on OBJ meshes without vertex normals.
    normals = vertex_normals(vertices, faces)
    lines = [f'# {name}, generated by generate_assets.py', f'o {name}']
    lines.extend(f'v {format_float(x)} {format_float(y)} {format_float(z)}' for x, y, z in vertices)
    lines.extend(f'vn {format_float(x)} {format_float(y)} {format_float(z)}' for x, y, z in normals)
    lines.extend(f'f {a + 1}//{a + 1} {b + 1}//{b + 1} {c + 1}//{c + 1}' for a, b, c in faces)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', newline='\n') as handle:
        handle.write('\n'.join(lines) + '\n')


def crater_height(x, y):
    # The cosine bowl has zero slope at the rim and the centre, so the
    # physics engine sees no sharp edge.
    z = 0.0
    for crater in CRATERS:
        radius = crater.diameter / 2.0
        r = math.hypot(x - crater.x, y - crater.y)
        if r < radius:
            z += -crater.depth * 0.5 * (1.0 + math.cos(math.pi * r / radius))
    return z


def build_terrain():
    columns = round(ARENA_LENGTH / GRID_STEP) + 1
    rows = round(ARENA_WIDTH / GRID_STEP) + 1
    vertices = []
    for j in range(rows):
        for i in range(columns):
            x = i * GRID_STEP
            y = j * GRID_STEP
            vertices.append((x, y, crater_height(x, y)))
    faces = []
    for j in range(rows - 1):
        for i in range(columns - 1):
            bottom_left = j * columns + i
            bottom_right = bottom_left + 1
            top_right = bottom_right + columns
            top_left = bottom_left + columns
            faces.append((bottom_left, bottom_right, top_right))
            faces.append((bottom_left, top_right, top_left))
    return vertices, faces


def icosphere(subdivisions):
    golden_ratio = (1.0 + math.sqrt(5.0)) / 2.0
    g = golden_ratio
    raw = [
        (-1, g, 0), (1, g, 0), (-1, -g, 0), (1, -g, 0),
        (0, -1, g), (0, 1, g), (0, -1, -g), (0, 1, -g),
        (g, 0, -1), (g, 0, 1), (-g, 0, -1), (-g, 0, 1),
    ]
    vertices = [normalise(v) for v in raw]
    faces = [
        (0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
        (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
        (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1),
    ]
    for _ in range(subdivisions):
        cache = {}

        def midpoint(p, q):
            key = (min(p, q), max(p, q))
            if key not in cache:
                m = tuple((vertices[p][k] + vertices[q][k]) / 2.0 for k in range(3))
                vertices.append(normalise(m))
                cache[key] = len(vertices) - 1
            return cache[key]

        new_faces = []
        for a, b, c in faces:
            ab = midpoint(a, b)
            bc = midpoint(b, c)
            ca = midpoint(c, a)
            new_faces.extend([(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)])
        faces = new_faces
    return vertices, faces


def build_rock(rock):
    rng = random.Random(rock.seed)
    vertices, faces = icosphere(ICOSPHERE_SUBDIVISIONS)

    # Noise and burying change the size, so the rock is rescaled to the
    # exact target size afterwards.
    shaped = []
    for x, y, z in vertices:
        k = 1.0 + ROCK_NOISE * (2.0 * rng.random() - 1.0)
        shaped.append((x * rock.length / 2.0 * k, y * rock.width / 2.0 * k, z * rock.height / 2.0 * k))

    zs = [v[2] for v in shaped]
    shift = ROCK_BURY * (max(zs) - min(zs))
    # Clamping flattens the base so the rock sits on the ground.
    buried = [(x, y, max(z - shift, 0.0)) for x, y, z in shaped]

    xs = [v[0] for v in buried]
    ys = [v[1] for v in buried]
    zs = [v[2] for v in buried]
    cx = (max(xs) + min(xs)) / 2.0
    cy = (max(ys) + min(ys)) / 2.0
    sx = rock.length / (max(xs) - min(xs))
    sy = rock.width / (max(ys) - min(ys))
    sz = rock.height / max(zs)
    final = [((x - cx) * sx, (y - cy) * sy, z * sz) for x, y, z in buried]
    return final, faces


def generate(output_dir):
    output_dir = Path(output_dir)
    vertices, faces = build_terrain()
    write_obj(output_dir / 'moon_yard_terrain' / 'meshes' / 'terrain.obj', 'terrain', vertices, faces)
    for name, rock in ROCKS.items():
        vertices, faces = build_rock(rock)
        write_obj(output_dir / name / 'meshes' / 'rock.obj', name, vertices, faces)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--output-dir', required=True)
    args = parser.parse_args()
    generate(args.output_dir)


if __name__ == '__main__':
    main()
