#!/usr/bin/env python3
"""Generate the terrain and rock meshes for the Moon Yard worlds.

Uses the standard library only. The output is deterministic: running the
script twice writes byte-identical files.

Usage: generate_assets.py [--output-dir DIR]
DIR defaults to the package ``models`` directory.
"""

import argparse
import math
import random
from pathlib import Path

ARENA_X = 7.9
ARENA_Y = 4.4
GRID_STEP = 0.05

# (centre x, centre y, diameter, depth) in arena coordinates, metres.
CRATERS = (
    (3.64, 4.00, 0.50, 0.12),
    (3.57, 1.90, 0.45, 0.15),
    (7.44, 2.00, 0.50, 0.18),
)

# name: (seed, footprint x, footprint y, height) in metres.
ROCKS = {
    'rock_a': (11, 0.38, 0.32, 0.22),
    'rock_b': (22, 0.34, 0.30, 0.18),
    'rock_c': (33, 0.40, 0.36, 0.25),
    'rock_d': (44, 0.31, 0.30, 0.16),
}

ROCK_NOISE = 0.15
ROCK_BURY = 0.25
ICOSPHERE_SUBDIVISIONS = 2


def fmt(value):
    text = f'{value:.6f}'
    return '0.000000' if text == '-0.000000' else text


def vertex_normals(vertices, faces):
    sums = [[0.0, 0.0, 0.0] for _ in vertices]
    for a, b, c in faces:
        pa, pb, pc = vertices[a], vertices[b], vertices[c]
        u = [pb[k] - pa[k] for k in range(3)]
        v = [pc[k] - pa[k] for k in range(3)]
        n = (u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0])
        for i in (a, b, c):
            for k in range(3):
                sums[i][k] += n[k]
    normals = []
    for n in sums:
        length = math.sqrt(sum(c * c for c in n)) or 1.0
        normals.append(tuple(c / length for c in n))
    return normals


def write_obj(path, name, vertices, faces):
    normals = vertex_normals(vertices, faces)
    lines = [f'# {name}, generated by generate_assets.py', f'o {name}']
    lines.extend(f'v {fmt(x)} {fmt(y)} {fmt(z)}' for x, y, z in vertices)
    lines.extend(f'vn {fmt(x)} {fmt(y)} {fmt(z)}' for x, y, z in normals)
    lines.extend(f'f {a + 1}//{a + 1} {b + 1}//{b + 1} {c + 1}//{c + 1}' for a, b, c in faces)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', newline='\n') as handle:
        handle.write('\n'.join(lines) + '\n')


def crater_height(x, y):
    z = 0.0
    for cx, cy, diameter, depth in CRATERS:
        radius = diameter / 2.0
        r = math.hypot(x - cx, y - cy)
        if r < radius:
            z += -depth * 0.5 * (1.0 + math.cos(math.pi * r / radius))
    return z


def build_terrain():
    nx = round(ARENA_X / GRID_STEP) + 1
    ny = round(ARENA_Y / GRID_STEP) + 1
    vertices = []
    for j in range(ny):
        for i in range(nx):
            x = i * GRID_STEP
            y = j * GRID_STEP
            vertices.append((x, y, crater_height(x, y)))
    faces = []
    for j in range(ny - 1):
        for i in range(nx - 1):
            a = j * nx + i
            b = a + 1
            c = b + nx
            d = a + nx
            faces.append((a, b, c))
            faces.append((a, c, d))
    return vertices, faces


def icosphere(subdivisions):
    t = (1.0 + math.sqrt(5.0)) / 2.0
    raw = [
        (-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0),
        (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
        (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1),
    ]
    vertices = []
    for v in raw:
        n = math.sqrt(sum(c * c for c in v))
        vertices.append(tuple(c / n for c in v))
    faces = [
        (0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
        (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
        (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1),
    ]
    for _ in range(subdivisions):
        cache = {}

        def midpoint(p, q):
            key = (min(p, q), max(p, q))
            if key not in cache:
                m = tuple((vertices[p][k] + vertices[q][k]) / 2.0 for k in range(3))
                n = math.sqrt(sum(c * c for c in m))
                vertices.append(tuple(c / n for c in m))
                cache[key] = len(vertices) - 1
            return cache[key]

        new_faces = []
        for a, b, c in faces:
            ab = midpoint(a, b)
            bc = midpoint(b, c)
            ca = midpoint(c, a)
            new_faces.extend([(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)])
        faces = new_faces
    return vertices, faces


def merge_duplicates(vertices, faces):
    index = {}
    merged = []
    remap = []
    for v in vertices:
        key = tuple(round(c, 6) for c in v)
        if key not in index:
            index[key] = len(merged)
            merged.append(v)
        remap.append(index[key])
    new_faces = []
    for a, b, c in faces:
        a, b, c = remap[a], remap[b], remap[c]
        if a != b and b != c and a != c:
            new_faces.append((a, b, c))
    return merged, new_faces


def build_rock(seed, footprint_x, footprint_y, height):
    rng = random.Random(seed)
    vertices, faces = icosphere(ICOSPHERE_SUBDIVISIONS)

    # Ellipsoid with radial noise. The height is scaled to the target later.
    shaped = []
    for x, y, z in vertices:
        k = 1.0 + ROCK_NOISE * (2.0 * rng.random() - 1.0)
        shaped.append((x * footprint_x / 2.0 * k, y * footprint_y / 2.0 * k, z * height / 2.0 * k))

    zs = [v[2] for v in shaped]
    shift = ROCK_BURY * (max(zs) - min(zs))
    buried = [(x, y, max(z - shift, 0.0)) for x, y, z in shaped]
    buried, faces = merge_duplicates(buried, faces)

    xs = [v[0] for v in buried]
    ys = [v[1] for v in buried]
    zs = [v[2] for v in buried]
    cx = (max(xs) + min(xs)) / 2.0
    cy = (max(ys) + min(ys)) / 2.0
    sx = footprint_x / (max(xs) - min(xs))
    sy = footprint_y / (max(ys) - min(ys))
    sz = height / max(zs)
    final = [((x - cx) * sx, (y - cy) * sy, z * sz) for x, y, z in buried]
    return final, faces


def generate(output_dir):
    output_dir = Path(output_dir)
    vertices, faces = build_terrain()
    write_obj(output_dir / 'moon_yard_terrain' / 'meshes' / 'terrain.obj', 'terrain', vertices, faces)
    for name, (seed, fx, fy, h) in sorted(ROCKS.items()):
        vertices, faces = build_rock(seed, fx, fy, h)
        write_obj(output_dir / name / 'meshes' / 'rock.obj', name, vertices, faces)


def main():
    default = Path(__file__).resolve().parent.parent / 'models'
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--output-dir', default=str(default))
    args = parser.parse_args()
    generate(args.output_dir)


if __name__ == '__main__':
    main()
