#!/usr/bin/env python3
import os
import sys

from ament_index_python.packages import get_package_prefix, get_package_share_directory


def main():
    executable = os.path.join(
        get_package_prefix('teleop_twist_keyboard'), 'lib', 'teleop_twist_keyboard', 'teleop_twist_keyboard')
    params = os.path.join(get_package_share_directory('innex_sim'), 'config', 'teleop_keyboard.yaml')
    os.execv(executable, [executable, '--ros-args', '--params-file', params, *sys.argv[1:]])


if __name__ == '__main__':
    main()
